apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    namespace: shivam
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - image: 96385274/py-mongo-container
          name: app
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: app-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/J/development/p1
          name: app-hostpath0
status: {}
